roll: d6>5
default_char: capiroto
chars:
        capiroto:
                strength: 2
                logic: 5
                hacking: 5
                exploit: 5
                edge: 4
                firearms: 2
                agility: 2
recipes:
        hack:
                type: extended
                attrs:
                        - hacking
                        - exploit
        burst:
                type: simple
                attrs:
                        - agility
                        - firearms
                mods: -2

